### ISSUE TITLE
Update server when image/container is run

### ISSUE THREAD

**Issue by p0kR** [sethmachine/valheim-server-docker#5]
### Issue
As mentioned in the README, the image has to be rebuilt when a new server version is released.  

### Possible solution
I think this can be fixed by doing the following things:
1. Call `steamcmd.sh` in the script executed at `ENTRYPOINT` instead of in the Dockerfile
    - This way it is executed everytime an image of the container is run
2. Do not install the server files in the image, but install it in a volume for persistent data, like it is done for the server data
    - This way steamcmd would update the server files at startup only if an update has been released

**Comment by p0kR** [comment]
Sadly I think I won't have the time to try this out in the next few weeks.  
But if I have the time to try it and make a PR, I will work on top of #4, it would be great if it is merged by then.

**Comment by sethmachine** [comment]
Yes this is definitely on my radar as next item TODO.  The approach I've been thinking of is using the `steamcmd` APIs to poll for updates and then if an update exists, stop the server (maybe issue an message to the owner letting them know), update the Valheim server and then start again.
